### PR TITLE
Rectified the typos from onwca/Onwca to ownca/Ownca

### PR DESCRIPTION
**Pull request by Lakshayainani**
Rectified the typos from onwca/Onwca to ownca/Ownca in the following files:
exceptions.py
keys.py
ownca.py
test_keys.py
test_ownca.py

### CODE REVIEW

**Review by KAUTH — APPROVED** [review]
Thank you for the PR @Lakshayainani! It looks good to me 😊

**Comment by Lakshayainani** [comment]
Closes https://github.com/OwnCA/ownca/issues/78

**Comment by Lakshayainani** [comment]
@kairoaraujo Anything pending on this PR before merging?

**Comment by kairoaraujo** [comment]
@Lakshayainani, no. I see @KAUTH comments, he didn't approve in the GH, but I can do it and merge.
Thank you for your contribution. ❤️ 
I will be releasing a new version end of the week probable 😃

**Review by kairoaraujo — APPROVED** [review]

**Pull request merged**
