### PR TITLE
Feature/non ca certs

### PR DESCRIPTION
**Pull request by ProjectZero4**
Hey guys, seems like my last attempt at this didn't cover all bases. I've now made it possible to issue a certificate like how the readme example shows but by specifiying ca=False the certificate can be implicity trusted by the browser as long as the CA cert is trusted.

### CODE REVIEW

**Review by lawndoc — APPROVED** [review]

**Comment by lawndoc** [comment]
We'll have to have @kairoaraujo kick off our automated tests before we can merge, it looks like I don't have permissions to do that.

**Comment by kairoaraujo** [comment]
Thank you, @ProjectZero4, for the PR! 🎉

The test errors are from GitHub actions. It's not stable for some reason. 

Is it possible to do some unit tests for the new parameter?

If also a functional test is possible would be even better, but the functional tests are not a must. Maybe we can create an issue to add a functional test using some browser client for this feature specific.

**Comment by kairoaraujo** [comment]
> Sure thing, I've been a little busy over the last week or so, but I'll see if I can get something together soon

👍
Thanks! the important thing for now is the UT, having it we are ready to merge.

**Comment by karamanolev** [comment]
@lawndoc @ProjectZero4 Any chance to get this merged and published on pypi? It is currently preventing Chrome and Firefox from accepting the issued certificates (which you might already know). I applied an equivalent fix locally and it resolves the issue. Do you need any help getting it done? It would definitely simplify things being able to use the official package.

**Comment by kairoaraujo** [comment]
@ProjectZero4 any progress with the UT? Can I add it?

**Comment by ProjectZero4** [comment]
Sorry guys, I've been super busy with work and completely forgot about this. Hope it wasn't too much of an inconvience!

**Comment by ProjectZero4** [comment]
Glad to see it got sorted though!

**Comment by kairoaraujo** [comment]
No worries @ProjectZero4. Thank you for your contribution.

**Comment by karamanolev** [comment]
Thanks all for get this through!

**Comment by kairoaraujo** [comment]
@karamanolev I will try to release the 0.4.0 today. Thank you!

**Pull request merged**
