### PR TITLE
handle empty OID args

### PR DESCRIPTION
**Pull request by lawndoc**
The changes skip adding the OID if it exists in oids_parameters but is empty

I ran into this issue in [CAPy](https://github.com/lawndoc/CAPy) when dynamically adding OIDs with blank defaults.

### CODE REVIEW

**Comment by lawndoc** [comment]
My code that is causing this issue is grabbing values from a request's json if it exists, and if not replaces it with a default value of an empty string.

My code that causes the issue:
```python3
...
certOids = {"country_name": request.json.get("C", ""),
            "state_or_province": request.json.get("ST", ""),
            "locality_name": request.json.get("L", ""),
            "street_address": request.json.get("A", ""),
            "organization_name": request.json.get("O", ""),
            "organization_unit_name": request.json.get("OU", ""),
            "email_address": request.json.get("E", "")}
...
serverCert = ca.issue_certificate(hostname=certHostname,
                                  maximum_days=certMaxDays,
                                  common_name=certCommonName,
                                  dns_names=certDnsNames,
                                  oids=certOids,
                                  public_exponent=certPublicExponent,
                                  key_size=certKeySize)
```

I think that passing in valid OIDs with empty values may be a common enough use case that it warrants the change in my pull request.

**Review by kairoaraujo — CHANGES_REQUESTED** [review]
Hi @lawndoc, thank you for your PR.

I added some comments.
Could you also add some unit tests for this case?

**Comment by lawndoc** [comment]
I'm new to unittest in Python. I understand the general structure of your tests and have a little experience with pytest, but there are a couple of things with the tests that I need explained. I see some variables such as `fake_certificate` and `sample_oids` and `ownca_certdata` being passed into tests, but I don't see where they are being set. Is that data generated by pytest when the tests are run or where does that come from?

**Comment by lawndoc** [comment]
Ah nevermind I found where they are declared, they're pytest fixtures in conftest.py. I just didn't explore the codebase enough :)

I'll add a fixture to make empty_oids and add a test using that.

**Comment by kairoaraujo** [comment]
> Ah nevermind I found where they are declared, they're pytest fixtures in conftest.py. I just didn't explore the codebase enough :)

Yes, it is a fixture.
 
> I'll add a fixture to make empty_oids and add a test using that.

You can do it even simpler, reusing the existent fixture.

```python
def test_format_oids_empty_strings(oids_sample):
    for oid in oids_sample:
        oids_sample[oid] = ""
        
    ....
    
```

I also suggest to add a test case where the values are None.

Thank you!

**Comment by lawndoc** [comment]
I made the requested changes and added a test. Let me know if there's anything else that needs taken care of.

**Review by kairoaraujo — APPROVED** [review]

**Pull request merged**
